// Script:    testepeca.script
// Autores:   Gabriel Barbosa de Oliveira
//            Guilherme de Azevedo Pereira Marques
//            Thiago Duarte Naves
// Data:      27/09/2015
// Propósito: Testar o módulo peça
//
// Esse teste é completo
//

== Criar uma peça
=criar 0 0 0

== Criar outra peça de outra cor
=criar 1 1 0

== Obter cor da peça 0
=obtercor  0 0 0

== Destruir a peça 0
=destruir 0 0

== Obter cor da peça 1
=obtercor 1 1 0

== Destruir a peça 1
=destruir 1 0

//fim

